# local.yml - Nakama configuration pour Render

console:
  max_message_size_bytes: 409600

logger:
  level: "debug"

runtime:
  js_entrypoint: "build/index.js"
  js_max_count: 128

socket:
  max_message_size_bytes: 4096
  max_request_size_bytes: 131072

matchmaker:
  interval_sec: 3

# La section database est commentée car Nakama utilise DATABASE_URL
# Nakama va automatiquement récupérer la connexion PostgreSQL via la variable d'environnement DATABASE_URL
# database:
#   driver: postgres
#   addresses:
#     - postgresql://user:password@host:5432/dbname?sslmode=require
